# Generated by Django 2.1.2 on 2018-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_title', models.CharField(max_length=200)),
                ('reward_description', models.CharField(max_length=500)),
                ('point_value', models.IntegerField(default=0)),
            ],
        ),
    ]
